# Generated by Django 5.2.8 on 2025-11-10 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_number', models.CharField(max_length=10, unique=True, verbose_name='Nº da Vaga')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Ocupado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': ('Numero da Vaga',),
                'verbose_name_plural': 'Número das Vagas',
            },
        ),
        migrations.CreateModel(
            name='ParkingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='Horário de Entrada')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Horário de Saída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_records', to='vehicle.vehicle', verbose_name='Veículo')),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_spot', to='parking.parkingspot', verbose_name='Local da Vaga')),
            ],
            options={
                'verbose_name': ('Registro de Vaga',),
                'verbose_name_plural': 'Registros de Vagas',
            },
        ),
    ]
