# Generated by Django 5.2.8 on 2025-11-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingrecord',
            options={'verbose_name': ('Registro da Vaga',), 'verbose_name_plural': 'Registro das Vagas'},
        ),
        migrations.AlterModelOptions(
            name='parkingspot',
            options={'verbose_name': ('Vaga',), 'verbose_name_plural': 'Vagas'},
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='spot_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Vaga'),
        ),
    ]
