# Generated by Django 5.2.8 on 2025-11-10 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': ('Tipo de Veículo',),
                'verbose_name_plural': 'Tipos de Veículos',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Customer', to='customer.customer', verbose_name='Proprietário')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Vehicle', to='vehicle.vehicletype', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': ('Veículo',),
                'verbose_name_plural': 'Veículos',
            },
        ),
    ]
